In [1]:
#This notebook tells us how to manipulate matrices in python 
#(Source : https://www.programiz.com/python-programming/matrix)

In [19]:
#Importing necessary packages
import numpy as np

In [20]:
#Deifing 3X2 matrix
A = np.array([[2, 4, 6], [5, -6, 1]])
print(A)


[[ 2  4  6]
 [ 5 -6  1]]


In [21]:
print(A[1])

[ 5 -6  1]


In [22]:
print(A[0])

[2 4 6]


In [23]:
print(A[1][2])

1


In [24]:
#Editing a particular element of A
A[1][1]=10

In [25]:
print(A)

[[ 2  4  6]
 [ 5 10  1]]


In [28]:
#Defining a second array
B = np.array([[-1, 5, 10], [2, -3, 1]])

In [30]:
#sum of two matrices
C=A+B
print("A=",A)
print("B=",B)
print("A+B=",C)

A= [[ 2  4  6]
 [ 5 10  1]]
B= [[-1  5 10]
 [ 2 -3  1]]
A+B= [[ 1  9 16]
 [ 7  7  2]]


In [31]:
#Transposing a matrix
BT=B.transpose()
print("B=",B)
print("B_T=",BT)

B= [[-1  5 10]
 [ 2 -3  1]]
B_T= [[-1  2]
 [ 5 -3]
 [10  1]]


In [32]:
#matrix multiplication
D=A.dot(BT)
print("AXB=",D)

AXB= [[ 78  -2]
 [ 55 -19]]


In [33]:
#Last element of last row is
print(A[-1][-1])

1


In [35]:
#rows of matrix
print(D[0]) #first row
print(D[-1]) #last row

[78 -2]
[ 55 -19]


In [37]:
#columns of a matrix
print(D[:,1]) #second column
print(A[:,0]) #first column

[ -2 -19]
[2 5]


In [38]:
#slicing of a matrix
L=np.array([1,2,3,4,5,6,7,7,8,9,8])

In [39]:
print(L[:3]) #print elements indexed 0,1,2

[1 2 3]


In [40]:
print(L[1:4]) #print elements indexed 1,2,3

[2 3 4]


In [41]:
print(L[2:]) #print elements from index 2

[3 4 5 6 7 7 8 9 8]


In [45]:
#New matrix
A1 = np.array([[1, 4, 5, 12, 14], 
    [-5, 8, 9, 0, 17],
    [-6, 7, 11, 19, 21]])

print(A1[:2, :4])

[[ 1  4  5 12]
 [-5  8  9  0]]


In [46]:
print(A1[1:,3:])

[[ 0 17]
 [19 21]]


In [48]:
#Adding a new row (https://stackoverflow.com/questions/3881453/numpy-add-row-to-array)
newrow = [1,2,3,4,5]
A1 = np.vstack([A1, newrow])
print(A1)

[[ 1  4  5 12 14]
 [-5  8  9  0 17]
 [-6  7 11 19 21]
 [ 1  2  3  4  5]]


In [50]:
#Adding a column (https://www.kite.com/python/answers/how-to-add-a-column-to-a-numpy-array-in-python)
new_column = [[3], [6], [3], [8]]
A1 = np.append(A1, new_column, axis=1)
print(A1)

[[ 1  4  5 12 14  3]
 [-5  8  9  0 17  6]
 [-6  7 11 19 21  3]
 [ 1  2  3  4  5  8]]


In [53]:
#Dimensions
print(len(A1)) #number of rows
print(len(A1[0])) #number of columns

4
6
